version: '2'
services:
# one service per file to be accessed by docker
  front-end: 
    build: './front-end'
#image:  'merits:front-end'
#    volumes:
#    - ./front-end/src/app
    ports:
      - "4200:4200"
      - "8080:4200"

  express-server:
    build: "."
   # image: "merits:express-server"
    ports:
    - "8000:8000"

  # mongodb:
  #   image: "merits:mongodb"
  #   ports: "27017:27017"

