version: "2"

services:
# one service per file to be accessed by docker
  
  front-end: 
    build: './front-end'
    image: "node:8"
    env_file: .env
    working_dir: ./front-end
    image: 'merits:front-end'
    volumes:
      - ./front-end/src/app
    ports:
      - "4200:4200"

  express-server:
    build: "./"
    image: "node:8"
    env_file: .env
    working_dir: ./
    image: "merits:express-server"
    volumes:
      -./home/node/server
    ports:
    - "3000:3000"

  

  # mongodb:
  #   image: "merits:mongodb"
  #   ports: "27017:27017"

