version: "3.3"

services:

  mongodb:
    # build: './mongo'
    image: 'mongo:latest'
    ports: 
    - "27017:27017"
    networks:
    - appnet

  front-end:
    build: './front-end'
    ports: 
      - '4200:4200'
      - '49153:49153'
    volumes:
      - './front-end:/usr/src/app'
    depends_on: 
      - mongodb
    networks:
      - appnet

  express-server:
    build: './server'
    ports: 
      - '3000:8000'
    volumes:
      - './server:/home/node/server'
    depends_on: 
      - mongodb
    networks:
      - appnet

networks:
  appnet: 















