version: "3.3"

services:
  front-end:
    build: './front-end'
    ports: 
      - '4200:4200'
    volumes:
      - './front-end:/home/front-end'

  express-server:
    build: '.'
    ports: 
      - '3000:3000'
    volumes:
      - '.:/home/server'
    


















