version: "3.3"

services:
  front-end:
    build: './front-end'
    ports: 
      - '4200:4200'
      - '49153:49153'
    volumes:
      - './front-end:/usr/src/app'

  express-server:
    build: './server'
    ports: 
      - '3000:8000'
    volumes:
      - './server:/home/node/server'
    


















